import type { AppTool } from '@sdkwork/autocut-types';

export type AutoCutToolDefinition = Omit<AppTool, 'name' | 'description'> & {
  nameKey: string;
  descriptionKey: string;
  defaultName: string;
  defaultDescription: string;
};

export const AUTOCUT_TOOL_DEFINITIONS: AutoCutToolDefinition[] = [
  {
    id: 'slicer',
    nameKey: 'tool.slicer.name',
    defaultName: 'Smart video slicing',
    icon: 'scissors',
    category: 'ai',
    descriptionKey: 'tool.slicer.description',
    defaultDescription: 'AI-assisted highlight extraction for continuous publishable video clips.',
    route: '/slicer',
  },
  {
    id: 'extractor-text',
    nameKey: 'tool.extractorText.name',
    defaultName: 'Text extraction',
    icon: 'file-text',
    category: 'ai',
    descriptionKey: 'tool.extractorText.description',
    defaultDescription: 'Extract accurate segmented text from local video or audio.',
    route: '/extractor-text',
  },
  {
    id: 'extractor-audio',
    nameKey: 'tool.extractorAudio.name',
    defaultName: 'Audio extraction',
    icon: 'music',
    category: 'audio',
    descriptionKey: 'tool.extractorAudio.description',
    defaultDescription: 'Extract the source audio track from video as a reusable audio file.',
    route: '/extractor-audio',
  },
  {
    id: 'video-gif',
    nameKey: 'tool.videoGif.name',
    defaultName: 'Video to GIF',
    icon: 'image',
    category: 'video',
    descriptionKey: 'tool.videoGif.description',
    defaultDescription: 'Convert a video segment into a high-quality shareable GIF.',
    route: '/video-gif',
  },
  {
    id: 'video-compress',
    nameKey: 'tool.videoCompress.name',
    defaultName: 'Video compression',
    icon: 'minimize',
    category: 'video',
    descriptionKey: 'tool.videoCompress.description',
    defaultDescription: 'Reduce video file size while preserving practical visual quality.',
    route: '/video-compress',
  },
  {
    id: 'video-convert',
    nameKey: 'tool.videoConvert.name',
    defaultName: 'Video format conversion',
    icon: 'refresh-ccw',
    category: 'video',
    descriptionKey: 'tool.videoConvert.description',
    defaultDescription: 'Convert between common video formats such as MP4, AVI, and MKV.',
    route: '/video-convert',
  },
  {
    id: 'video-enhance',
    nameKey: 'tool.videoEnhance.name',
    defaultName: 'Video enhancement',
    icon: 'monitor',
    category: 'video',
    descriptionKey: 'tool.videoEnhance.description',
    defaultDescription: 'Improve low-quality source video with enhancement processing.',
    route: '/video-enhance',
  },
  {
    id: 'video-dedup',
    nameKey: 'tool.videoDedup.name',
    defaultName: 'Video deduplication',
    icon: 'copy',
    category: 'ai',
    descriptionKey: 'tool.videoDedup.description',
    defaultDescription: 'Detect exact, near-duplicate, audio, visual, semantic, and template reuse across videos.',
    route: '/video-dedup',
  },
  {
    id: 'subtitle-translate',
    nameKey: 'tool.subtitleTranslate.name',
    defaultName: 'Subtitle translation',
    icon: 'languages',
    category: 'ai',
    descriptionKey: 'tool.subtitleTranslate.description',
    defaultDescription: 'Recognize speech and generate translated subtitle timelines.',
    route: '/subtitle-translate',
  },
  {
    id: 'voice-translate',
    nameKey: 'tool.voiceTranslate.name',
    defaultName: 'Voice translation',
    icon: 'mic',
    category: 'ai',
    descriptionKey: 'tool.voiceTranslate.description',
    defaultDescription: 'Translate spoken content and synthesize localized voice output.',
    route: '/voice-translate',
  },
];
