import type { AppTool } from '@sdkwork/autocut-types';

export const INITIAL_TOOLS: AppTool[] = [
  {
    id: 'slicer',
    name: '视频智能切片',
    icon: 'scissors',
    category: 'ai',
    description: '基于大模型的智能视频片段提取方案，自动识别高光时刻',
    route: '/slicer',
  },
  {
    id: 'extractor-text',
    name: '文案提取',
    icon: 'file-text',
    category: 'ai',
    description: '从视频或音频中提取精准文字内容并分段落',
    route: '/extractor-text',
  },
  {
    id: 'extractor-audio',
    name: '视频提取音频',
    icon: 'music',
    category: 'audio',
    description: '一键无损提取视频中的音频轨道，支持导出 mp3、wav',
    route: '/extractor-audio',
  },
  {
    id: 'video-gif',
    name: '视频转 GIF',
    icon: 'image',
    category: 'video',
    description: '快速将视频片段转换为高画质、分享性强的动图',
    route: '/video-gif',
  },
  {
    id: 'video-compress',
    name: '视频压缩',
    icon: 'minimize',
    category: 'video',
    description: '智能降低视频体积，同时极限保持画质清晰',
    route: '/video-compress',
  },
  {
    id: 'video-convert',
    name: '视频格式转换',
    icon: 'refresh-ccw',
    category: 'video',
    description: '在 MP4/AVI/MKV 等多达十几款格式间无损转换',
    route: '/video-convert',
  },
  {
    id: 'video-enhance',
    name: '视频高清化',
    icon: 'monitor',
    category: 'video',
    description: '基于深度学习提升视频分辨率，拯救低画质原素材',
    route: '/video-enhance',
  },
  {
    id: 'subtitle-translate',
    name: '视频字幕翻译',
    icon: 'languages',
    category: 'ai',
    description: '自动识别语音，并翻译生成双语或多语种时间轴字幕',
    route: '/subtitle-translate',
  },
  {
    id: 'voice-translate',
    name: '视频人声翻译',
    icon: 'mic',
    category: 'ai',
    description: '克隆原声音色进行跨语种人声配音合成，实现本地化',
    route: '/voice-translate',
  },
];
