#!/usr/bin/env node

import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  createAutoCutPackageSbom,
  formatAutoCutPackageSbomFilesMessage,
  writeAutoCutPackageSbomFiles,
} from './write-autocut-package-sbom-files.mjs';
import { createAutoCutSbomEvidence } from './write-autocut-sbom-evidence.mjs';

const allPackageIds = [
  'desktop-windows-msi',
  'desktop-windows-nsis',
  'desktop-linux-deb',
  'desktop-linux-appimage',
  'desktop-macos-x64-dmg',
  'desktop-macos-aarch64-dmg',
];

function tempRoot(name) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `${name}-`));
}

function writeText(filePath, text) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, text);
}

function writeJson(filePath, payload) {
  writeText(filePath, `${JSON.stringify(payload, null, 2)}\n`);
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeFixture(root, { omitPnpmLock = false, omitCargoLock = false } = {}) {
  writeJson(path.join(root, 'package.json'), {
    name: '@sdkwork/video-cut',
    version: '9.8.7',
    private: true,
    packageManager: 'pnpm@10.30.2',
    dependencies: {
      '@sdkwork/autocut-desktop': 'workspace:*',
    },
    devDependencies: {
      typescript: 'catalog:',
    },
  });
  writeJson(path.join(root, 'packages', 'sdkwork-autocut-desktop', 'package.json'), {
    name: '@sdkwork/autocut-desktop',
    version: '9.8.7',
    private: true,
    dependencies: {
      '@sdkwork/autocut-core': 'workspace:*',
      '@tauri-apps/api': 'catalog:',
      react: 'catalog:',
    },
    devDependencies: {
      vite: 'catalog:',
    },
  });
  writeJson(path.join(root, 'packages', 'sdkwork-autocut-core', 'package.json'), {
    name: '@sdkwork/autocut-core',
    version: '9.8.7',
    private: true,
    dependencies: {
      react: 'catalog:',
      'react-router-dom': 'catalog:',
    },
  });
  writeText(
    path.join(root, 'packages', 'sdkwork-autocut-desktop', 'src-tauri', 'Cargo.toml'),
    `[package]
name = "sdkwork-video-cut-desktop"
version = "9.8.7"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "=2.10.3", features = ["protocol-asset"] }

[target.'cfg(windows)'.dependencies]
windows-native-keyring-store = "1.0.0"
`,
  );

  if (!omitPnpmLock) {
    writeText(
      path.join(root, 'pnpm-lock.yaml'),
      `lockfileVersion: '9.0'

catalogs:
  default:
    '@tauri-apps/api':
      specifier: 2.10.1
      version: 2.10.1
    react:
      specifier: ^19.0.0
      version: 19.2.5
    react-router-dom:
      specifier: ^7.14.0
      version: 7.14.2
    react-router:
      specifier: ^7.14.0
      version: 7.14.2
    cookie:
      specifier: ^1.1.1
      version: 1.1.1
    set-cookie-parser:
      specifier: ^2.7.2
      version: 2.7.2
    typescript:
      specifier: ~5.8.2
      version: 5.8.3
    vite:
      specifier: ^6.2.3
      version: 6.4.2

snapshots:
  react-router-dom@7.14.2(react-dom@19.2.5(react@19.2.5))(react@19.2.5):
    dependencies:
      react: 19.2.5
      react-dom: 19.2.5(react@19.2.5)
      react-router: 7.14.2(react-dom@19.2.5(react@19.2.5))(react@19.2.5)

  react-router@7.14.2(react-dom@19.2.5(react@19.2.5))(react@19.2.5):
    dependencies:
      cookie: 1.1.1
      react: 19.2.5
      set-cookie-parser: 2.7.2

  react@19.2.5: {}

  react-dom@19.2.5(react@19.2.5):
    dependencies:
      react: 19.2.5

  cookie@1.1.1: {}

  set-cookie-parser@2.7.2: {}
`,
    );
  }

  if (!omitCargoLock) {
    writeText(
      path.join(root, 'packages', 'sdkwork-autocut-desktop', 'src-tauri', 'Cargo.lock'),
      `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "sdkwork-video-cut-desktop"
version = "9.8.7"
dependencies = [
 "serde 1.0.228",
 "tauri",
 "windows-native-keyring-store",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
dependencies = [
 "serde_derive 1.0.228",
]

[[package]]
name = "serde_derive"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "4444444444444444444444444444444444444444444444444444444444444444"

[[package]]
name = "serde_derive"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5555555555555555555555555555555555555555555555555555555555555555"

[[package]]
name = "tauri"
version = "2.10.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222222222"

[[package]]
name = "windows-native-keyring-store"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3333333333333333333333333333333333333333333333333333333333333333"
`,
    );
  }
}

const completeRoot = tempRoot('autocut-package-sbom-complete');
writeFixture(completeRoot);
const written = writeAutoCutPackageSbomFiles({
  rootDir: completeRoot,
  generatedAt: '2026-05-08T00:00:00.000Z',
});

assert.equal(written.files.length, 6);
assert.deepEqual(
  written.files.map((file) => file.packageId),
  allPackageIds,
);
assert.equal(
  formatAutoCutPackageSbomFilesMessage(written),
  `ok - autocut package SBOM files ${path.join(completeRoot, 'artifacts', 'release', 'sbom')} packages=6 components=80`,
);

const windowsSbom = readJson(path.join(completeRoot, 'artifacts', 'release', 'sbom', 'desktop-windows-msi.cdx.json'));
assert.equal(windowsSbom.bomFormat, 'CycloneDX');
assert.equal(windowsSbom.specVersion, '1.6');
assert.equal(windowsSbom.metadata.component.name, 'SDKWork Video Cut desktop-windows-msi');
assert.equal(windowsSbom.metadata.component.version, '9.8.7');
assert.ok(windowsSbom.serialNumber.startsWith('urn:uuid:'));
assert.ok(
  windowsSbom.metadata.properties.some(
    (property) => property.name === 'sdkwork:autocut:packageId' && property.value === 'desktop-windows-msi',
  ),
);
assert.ok(
  windowsSbom.metadata.properties.some(
    (property) => property.name === 'sdkwork:autocut:platform' && property.value === 'windows-x86_64',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) => component.name === '@sdkwork/autocut-desktop' && component.version === '9.8.7',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) => component.name === '@sdkwork/autocut-core' && component.version === '9.8.7',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) => component.name === 'react' && component.version === '19.2.5',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) => component.name === 'react-router' && component.version === '7.14.2',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) => component.name === 'cookie' && component.version === '1.1.1',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) => component.name === 'set-cookie-parser' && component.version === '2.7.2',
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) =>
      component.name === 'serde' &&
      component.version === '1.0.228' &&
      component.hashes.some((hash) => hash.alg === 'SHA-256'),
  ),
);
assert.ok(
  windowsSbom.components.some(
    (component) =>
      component.name === 'serde_derive' &&
      component.version === '1.0.228' &&
      component.hashes.some((hash) => hash.content === '4444444444444444444444444444444444444444444444444444444444444444'),
  ),
);
assert.equal(
  windowsSbom.components.some(
    (component) =>
      component.name === 'serde_derive' &&
      component.version === '2.0.0',
  ),
  false,
);
assert.ok(
  windowsSbom.components.some(
    (component) =>
      component.name === 'windows-native-keyring-store' &&
      component.version === '1.0.0',
  ),
);
assert.ok(
  windowsSbom.dependencies.some(
    (entry) =>
      entry.ref === 'pkg:generic/sdkwork-video-cut@9.8.7?package-id=desktop-windows-msi' &&
      entry.dependsOn.length > 0,
  ),
);

const linuxSbom = readJson(path.join(completeRoot, 'artifacts', 'release', 'sbom', 'desktop-linux-deb.cdx.json'));
assert.equal(
  linuxSbom.components.some((component) => component.name === 'windows-native-keyring-store'),
  false,
);

const evidence = createAutoCutSbomEvidence({
  rootDir: completeRoot,
  releaseTag: 'v9.8.7',
  generatedAt: '2026-05-08T00:00:00.000Z',
});
assert.equal(evidence.readiness.sbomReady, true);
assert.equal(evidence.packages.length, 6);

const platformRoot = tempRoot('autocut-package-sbom-platform');
writeFixture(platformRoot);
const platformWritten = writeAutoCutPackageSbomFiles({
  rootDir: platformRoot,
  platform: 'linux-x86_64',
  generatedAt: '2026-05-08T00:00:00.000Z',
});
assert.deepEqual(
  platformWritten.files.map((file) => file.packageId),
  ['desktop-linux-deb', 'desktop-linux-appimage'],
);

const singleSbom = createAutoCutPackageSbom({
  rootDir: completeRoot,
  packageId: 'desktop-macos-aarch64-dmg',
  generatedAt: '2026-05-08T00:00:00.000Z',
});
assert.equal(singleSbom.metadata.component.name, 'SDKWork Video Cut desktop-macos-aarch64-dmg');
assert.ok(
  singleSbom.metadata.properties.some(
    (property) => property.name === 'sdkwork:autocut:architecture' && property.value === 'aarch64',
  ),
);

assert.throws(
  () => writeAutoCutPackageSbomFiles({ rootDir: completeRoot, packageIds: ['desktop-web'] }),
  /Unsupported AutoCut release package id/u,
);

const missingPnpmLockRoot = tempRoot('autocut-package-sbom-missing-pnpm-lock');
writeFixture(missingPnpmLockRoot, { omitPnpmLock: true });
assert.throws(
  () => writeAutoCutPackageSbomFiles({ rootDir: missingPnpmLockRoot }),
  /missing AutoCut pnpm lockfile/u,
);

const missingCargoLockRoot = tempRoot('autocut-package-sbom-missing-cargo-lock');
writeFixture(missingCargoLockRoot, { omitCargoLock: true });
assert.throws(
  () => writeAutoCutPackageSbomFiles({ rootDir: missingCargoLockRoot }),
  /missing AutoCut Cargo lockfile/u,
);

const unresolvedNpmRoot = tempRoot('autocut-package-sbom-unresolved-npm');
writeFixture(unresolvedNpmRoot);
const unresolvedDesktopPackagePath = path.join(unresolvedNpmRoot, 'packages', 'sdkwork-autocut-desktop', 'package.json');
const unresolvedDesktopPackage = readJson(unresolvedDesktopPackagePath);
unresolvedDesktopPackage.dependencies['left-pad'] = '^1.3.0';
writeJson(unresolvedDesktopPackagePath, unresolvedDesktopPackage);
assert.throws(
  () => writeAutoCutPackageSbomFiles({ rootDir: unresolvedNpmRoot }),
  /unresolved AutoCut npm runtime dependency versions: left-pad/u,
);

const ambiguousCargoRoot = tempRoot('autocut-package-sbom-ambiguous-cargo');
writeFixture(ambiguousCargoRoot);
const ambiguousCargoLockPath = path.join(ambiguousCargoRoot, 'packages', 'sdkwork-autocut-desktop', 'src-tauri', 'Cargo.lock');
fs.writeFileSync(
  ambiguousCargoLockPath,
  fs.readFileSync(ambiguousCargoLockPath, 'utf8').replace('"serde_derive 1.0.228"', '"serde_derive"'),
);
assert.throws(
  () => writeAutoCutPackageSbomFiles({ rootDir: ambiguousCargoRoot }),
  /ambiguous AutoCut Cargo dependency reference: serde_derive/u,
);

console.log('ok - autocut package SBOM file writer contract');
