{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-sdkwork-video-cut-workspace
  labels:
    app.kubernetes.io/name: sdkwork-video-cut
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
{{ toYaml .Values.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
{{- end }}
