apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sdkwork-video-cut-secret
  labels:
    app.kubernetes.io/name: sdkwork-video-cut
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SDKWORK_VIDEO_CUT_OPENAI_COMPATIBLE_API_KEY: {{ .Values.secrets.aiApiKey | quote }}
  SDKWORK_VIDEO_CUT_STT_API_KEY: {{ .Values.secrets.speechToTextApiKey | quote }}
  SDKWORK_VIDEO_CUT_SERVER_TOKEN: {{ .Values.secrets.serverToken | quote }}
