apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sdkwork-video-cut
  labels:
    app.kubernetes.io/name: sdkwork-video-cut
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: sdkwork-video-cut
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: http
